languageCode = 'pl-pl'
paginate = 9
theme = "coHub"
title = 'Hackerspace Tr贸jmiasto'
DefaultContentLanguage = "pl"

[languages]
[languages.pl]
languageName = "叼"
contentDir = 'content/pl'

[languages.pl.params]
aboutPageURL = "blog"
contactLink = "/contact"
copyright = "漏 {year} Hackerspace Tr贸jmiasto"
googleAnalytics = ""
logo = "/images/logo.png"
footerlogo = "/images/logo.png"
footerDescription = "Przyjd藕 i zbuduj co z nami"

[languages.pl.params.address]
address = "al. Wojska Polskiego 41<br>80-268 Gdask"
email = "kontakt@hs3.pl"
openingDesc = "Otwarte ca dob dla os贸b z kluczem."
openingHours = "Jeli nie masz klucza [zapytaj na Discord](https://hs3.pl/join) czy kto jest w rodku."
phone = "+48 661 691 133"

[languages.en]
title = "Hackerspace Tr贸jmiasto (Three-city)"
contentDir = 'content/en'
languageName = ""

[languages.en.params]
aboutPageURL = "blog"
contactLink = "/en/contact"
copyright = "漏 {year} Hackerspace Tr贸jmiasto"
googleAnalytics = ""
logo = "/images/logo.png"
footerlogo = "/images/logo.png"
footerDescription = "Come and build with us"

[languages.en.params.address]
address = "al. Wojska Polskiego 41<br>80-268 Gdask"
email = "kontakt@hs3.pl"
openingDesc = "Open 24/7 for members with a key."
openingHours = "For members without key and non-members: [ask on Discord](https://hs3.pl/join) if someone is there (in English or Polish)."
phone = "+48 661 691 133"

[params.map]
APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
latitude = "54.3896193"
longitude = "18.58178"
pinImage = "/images/pin.png"

[Menu]
# Main Menu
[[menu.Main]]
identifier = "about-us"
pageref = "/about"
weight = 1
[[menu.Main]]
identifier = "events"
pageref = "/wydarzenia"
weight = 2
[[menu.Main]]
identifier = "projects"
pageref = "/projekty"
weight = 3
[[menu.Main]]
identifier = "blogs"
pageref = "/blog"
weight = 4
[[menu.Main]]
identifier = "membership"
pageref = "/zasoby/czlonkostwo"
weight = 5
[[menu.Main]]
identifier = "resources"
pageref = "/zasoby"
weight = 6
[[menu.Main]]
identifier = "FAQ"
url = "/#faq"
weight = 7
[[menu.Main]]
identifier = "contact"
url = "/#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "Privacy Policy"
url = "/privacy/"
weight = 1

# Socail icons
[[params.social]]
icon = "ti-facebook"
url = "https://www.facebook.com/hackerspacetrojmiasto"
weight = 1
[[params.social]]
icon = "ti-twitter-alt"
url = "https://twitter.com/hs3city"
weight = 2
[[params.social]]
icon = "ti-linkedin"
url = "https://www.linkedin.com/company/hackerspace-tr%C3%B3jmiasto/"
weight = 2
[[params.social]]
icon = "ti-user"
url = "https://hs3.pl/join"
weight = 3
[[params.social]]
icon = "ti-youtube"
url = "https://www.youtube.com/channel/UC1MjdZvgtGZwSAaveL-Z8CA"
weight = 4
[[params.social]]
icon = "ti-video-camera"
url = "https://www.twitch.tv/hs3city"
weight = 5  
[[params.social]]
icon = "ti-github"
url = "https://github.com/hs3city"
weight = 6
[[params.social]]
icon = "ti-wallet"
url = "https://patronite.pl/hs3/description"
weight = 7
